-- AlterTable
ALTER TABLE "airdrop" ALTER COLUMN "empty_rate" SET DEFAULT '',
ALTER COLUMN "empty_rate" SET DATA TYPE TEXT,
ALTER COLUMN "expected_income" SET DEFAULT '',
ALTER COLUMN "expected_income" SET DATA TYPE TEXT,
ALTER COLUMN "funding" SET DEFAULT '',
ALTER COLUMN "funding" SET DATA TYPE TEXT,
ALTER COLUMN "min_invest" SET DEFAULT '',
ALTER COLUMN "min_invest" SET DATA TYPE TEXT,
ALTER COLUMN "score" SET DEFAULT '',
ALTER COLUMN "score" SET DATA TYPE TEXT;
